// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using TheFipster.Aviation.Domain.Simbrief;
//
//    var simbriefImport = SimbriefImport.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace TheFipster.Aviation.Domain.Simbrief
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class SimbriefImport
    {
        [JsonPropertyName("fetch")]
        public Fetch Fetch { get; set; }

        [JsonPropertyName("params")]
        public Params Params { get; set; }

        [JsonPropertyName("general")]
        public General General { get; set; }

        [JsonPropertyName("origin")]
        public Origin Origin { get; set; }

        [JsonPropertyName("destination")]
        public Destination Destination { get; set; }

        [JsonPropertyName("alternate")]
        public List<Alternate> Alternate { get; set; }

        [JsonPropertyName("takeoff_altn")]
        public List<object> TakeoffAltn { get; set; }

        [JsonPropertyName("enroute_altn")]
        public List<object> EnrouteAltn { get; set; }

        [JsonPropertyName("navlog")]
        public List<Navlog> Navlog { get; set; }

        [JsonPropertyName("etops")]
        public List<object> Etops { get; set; }

        [JsonPropertyName("atc")]
        public Atc Atc { get; set; }

        [JsonPropertyName("aircraft")]
        public Aircraft Aircraft { get; set; }

        [JsonPropertyName("fuel")]
        public Fuel Fuel { get; set; }

        [JsonPropertyName("fuel_extra")]
        public FuelExtra FuelExtra { get; set; }

        [JsonPropertyName("times")]
        public Times Times { get; set; }

        [JsonPropertyName("weights")]
        public Weights Weights { get; set; }

        [JsonPropertyName("crew")]
        public Crew Crew { get; set; }

        [JsonPropertyName("notams")]
        public List<SimbriefImportNotam> Notams { get; set; }

        [JsonPropertyName("weather")]
        public Weather Weather { get; set; }

        [JsonPropertyName("sigmets")]
        public List<Sigmet> Sigmets { get; set; }

        [JsonPropertyName("text")]
        public Text Text { get; set; }

        [JsonPropertyName("tracks")]
        public List<object> Tracks { get; set; }

        [JsonPropertyName("database_updates")]
        public DatabaseUpdates DatabaseUpdates { get; set; }

        [JsonPropertyName("files")]
        public Files Files { get; set; }

        [JsonPropertyName("fms_downloads")]
        public FmsDownloads FmsDownloads { get; set; }

        [JsonPropertyName("images")]
        public Images Images { get; set; }

        [JsonPropertyName("links")]
        public Links Links { get; set; }

        [JsonPropertyName("prefile")]
        public Prefile Prefile { get; set; }

        [JsonPropertyName("vatsim_prefile")]
        public string VatsimPrefile { get; set; }

        [JsonPropertyName("ivao_prefile")]
        public string IvaoPrefile { get; set; }

        [JsonPropertyName("pilotedge_prefile")]
        public Uri PilotedgePrefile { get; set; }

        [JsonPropertyName("poscon_prefile")]
        public Uri PosconPrefile { get; set; }

        [JsonPropertyName("map_data")]
        public Uri MapData { get; set; }

        [JsonPropertyName("api_params")]
        public Dictionary<string, string> ApiParams { get; set; }
    }

    public partial class Aircraft
    {
        [JsonPropertyName("icaocode")]
        public string Icaocode { get; set; }

        [JsonPropertyName("iatacode")]
        public string Iatacode { get; set; }

        [JsonPropertyName("base_type")]
        public string BaseType { get; set; }

        [JsonPropertyName("icao_code")]
        public string IcaoCode { get; set; }

        [JsonPropertyName("iata_code")]
        public string IataCode { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("reg")]
        public string Reg { get; set; }

        [JsonPropertyName("fin")]
        public string Fin { get; set; }

        [JsonPropertyName("selcal")]
        public string Selcal { get; set; }

        [JsonPropertyName("equip")]
        public string Equip { get; set; }

        [JsonPropertyName("fuelfact")]
        public string Fuelfact { get; set; }

        [JsonPropertyName("fuelfactor")]
        public string Fuelfactor { get; set; }

        [JsonPropertyName("max_passengers")]
        public string MaxPassengers { get; set; }

        [JsonPropertyName("supports_tlr")]
        public string SupportsTlr { get; set; }

        [JsonPropertyName("internal_id")]
        public string InternalId { get; set; }

        [JsonPropertyName("is_custom")]
        public string IsCustom { get; set; }
    }

    public partial class Alternate
    {
        [JsonPropertyName("icao_code")]
        public string IcaoCode { get; set; }

        [JsonPropertyName("iata_code")]
        public string IataCode { get; set; }

        [JsonPropertyName("faa_code")]
        public string FaaCode { get; set; }

        [JsonPropertyName("icao_region")]
        public string IcaoRegion { get; set; }

        [JsonPropertyName("elevation")]
        public string Elevation { get; set; }

        [JsonPropertyName("pos_lat")]
        public string PosLat { get; set; }

        [JsonPropertyName("pos_long")]
        public string PosLong { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("timezone")]
        public string Timezone { get; set; }

        [JsonPropertyName("plan_rwy")]
        public string PlanRwy { get; set; }

        [JsonPropertyName("trans_alt")]
        public string TransAlt { get; set; }

        [JsonPropertyName("trans_level")]
        public string TransLevel { get; set; }

        [JsonPropertyName("cruise_altitude")]
        public string CruiseAltitude { get; set; }

        [JsonPropertyName("distance")]
        public string Distance { get; set; }

        [JsonPropertyName("gc_distance")]
        public string GcDistance { get; set; }

        [JsonPropertyName("air_distance")]
        public string AirDistance { get; set; }

        [JsonPropertyName("track_true")]
        public string TrackTrue { get; set; }

        [JsonPropertyName("track_mag")]
        public string TrackMag { get; set; }

        [JsonPropertyName("tas")]
        public string Tas { get; set; }

        [JsonPropertyName("gs")]
        public string Gs { get; set; }

        [JsonPropertyName("avg_wind_comp")]
        public string AvgWindComp { get; set; }

        [JsonPropertyName("avg_wind_dir")]
        public string AvgWindDir { get; set; }

        [JsonPropertyName("avg_wind_spd")]
        public string AvgWindSpd { get; set; }

        [JsonPropertyName("avg_tropopause")]
        public string AvgTropopause { get; set; }

        [JsonPropertyName("avg_tdv")]
        public string AvgTdv { get; set; }

        [JsonPropertyName("ete")]
        public string Ete { get; set; }

        [JsonPropertyName("burn")]
        public string Burn { get; set; }

        [JsonPropertyName("route")]
        public string Route { get; set; }

        [JsonPropertyName("route_ifps")]
        public string RouteIfps { get; set; }

        [JsonPropertyName("metar")]
        public string Metar { get; set; }

        [JsonPropertyName("metar_time")]
        public object MetarTime { get; set; }

        [JsonPropertyName("metar_category")]
        public object MetarCategory { get; set; }

        [JsonPropertyName("metar_visibility")]
        public object MetarVisibility { get; set; }

        [JsonPropertyName("metar_ceiling")]
        public object MetarCeiling { get; set; }

        [JsonPropertyName("taf")]
        public string Taf { get; set; }

        [JsonPropertyName("taf_time")]
        public object TafTime { get; set; }

        [JsonPropertyName("atis")]
        public List<object> Atis { get; set; }

        [JsonPropertyName("notam")]
        public List<AirportNotam> Notam { get; set; }
    }

    public partial class Atc
    {
        [JsonPropertyName("flightplan_text")]
        public string FlightplanText { get; set; }

        [JsonPropertyName("route")]
        public string Route { get; set; }

        [JsonPropertyName("route_ifps")]
        public string RouteIfps { get; set; }

        [JsonPropertyName("callsign")]
        public string Callsign { get; set; }

        [JsonPropertyName("initial_spd")]
        public string InitialSpd { get; set; }

        [JsonPropertyName("initial_spd_unit")]
        public string InitialSpdUnit { get; set; }

        [JsonPropertyName("initial_alt")]
        public string InitialAlt { get; set; }

        [JsonPropertyName("initial_alt_unit")]
        public string InitialAltUnit { get; set; }

        [JsonPropertyName("section18")]
        public string Section18 { get; set; }

        [JsonPropertyName("fir_orig")]
        public string FirOrig { get; set; }

        [JsonPropertyName("fir_dest")]
        public string FirDest { get; set; }

        [JsonPropertyName("fir_altn")]
        public List<string> FirAltn { get; set; }

        [JsonPropertyName("fir_etops")]
        public List<object> FirEtops { get; set; }

        [JsonPropertyName("fir_enroute")]
        public List<string> FirEnroute { get; set; }
    }

    public partial class Crew
    {
        [JsonPropertyName("pilot_id")]
        public string PilotId { get; set; }

        [JsonPropertyName("cpt")]
        public string Cpt { get; set; }

        [JsonPropertyName("fo")]
        public string Fo { get; set; }

        [JsonPropertyName("dx")]
        public string Dx { get; set; }

        [JsonPropertyName("pu")]
        public string Pu { get; set; }

        [JsonPropertyName("fa")]
        public List<string> Fa { get; set; }
    }

    public partial class DatabaseUpdates
    {
        [JsonPropertyName("metar_taf")]
        public string MetarTaf { get; set; }

        [JsonPropertyName("winds")]
        public string Winds { get; set; }

        [JsonPropertyName("sigwx")]
        public string Sigwx { get; set; }

        [JsonPropertyName("sigmet")]
        public string Sigmet { get; set; }

        [JsonPropertyName("notams")]
        public string Notams { get; set; }

        [JsonPropertyName("tracks")]
        public string Tracks { get; set; }
    }

    public partial class Destination
    {
        [JsonPropertyName("icao_code")]
        public string IcaoCode { get; set; }

        [JsonPropertyName("iata_code")]
        public string IataCode { get; set; }

        [JsonPropertyName("faa_code")]
        public string FaaCode { get; set; }

        [JsonPropertyName("icao_region")]
        public string IcaoRegion { get; set; }

        [JsonPropertyName("elevation")]
        public string Elevation { get; set; }

        [JsonPropertyName("pos_lat")]
        public string PosLat { get; set; }

        [JsonPropertyName("pos_long")]
        public string PosLong { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("timezone")]
        public string Timezone { get; set; }

        [JsonPropertyName("plan_rwy")]
        public string PlanRwy { get; set; }

        [JsonPropertyName("trans_alt")]
        public string TransAlt { get; set; }

        [JsonPropertyName("trans_level")]
        public string TransLevel { get; set; }

        [JsonPropertyName("metar")]
        public string Metar { get; set; }

        [JsonPropertyName("metar_time")]
        public object MetarTime { get; set; }

        [JsonPropertyName("metar_category")]
        public object MetarCategory { get; set; }

        [JsonPropertyName("metar_visibility")]
        public object MetarVisibility { get; set; }

        [JsonPropertyName("metar_ceiling")]
        public object MetarCeiling { get; set; }

        [JsonPropertyName("taf")]
        public string Taf { get; set; }

        [JsonPropertyName("taf_time")]
        public object TafTime { get; set; }

        [JsonPropertyName("atis")]
        public List<object> Atis { get; set; }

        [JsonPropertyName("notam")]
        public List<AirportNotam> Notam { get; set; }
    }

    public partial class Fetch
    {
        [JsonPropertyName("userid")]
        public string Userid { get; set; }

        [JsonPropertyName("static_id")]
        public string StaticId { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("time")]
        public string Time { get; set; }
    }

    public partial class Files
    {
        [JsonPropertyName("directory")]
        public Uri Directory { get; set; }

        [JsonPropertyName("pdf")]
        public Pdf Pdf { get; set; }

        [JsonPropertyName("file")]
        public List<Pdf> File { get; set; }
    }

    public partial class Pdf
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("link")]
        public string Link { get; set; }
    }

    public partial class FmsDownloads
    {
        [JsonPropertyName("directory")]
        public Uri Directory { get; set; }

        [JsonPropertyName("pdf")]
        public Pdf Pdf { get; set; }

        [JsonPropertyName("abx")]
        public Pdf Abx { get; set; }

        [JsonPropertyName("a3e")]
        public Pdf A3E { get; set; }

        [JsonPropertyName("crx")]
        public Pdf Crx { get; set; }

        [JsonPropertyName("cra")]
        public Pdf Cra { get; set; }

        [JsonPropertyName("psx")]
        public Pdf Psx { get; set; }

        [JsonPropertyName("efb")]
        public Pdf Efb { get; set; }

        [JsonPropertyName("ef2")]
        public Pdf Ef2 { get; set; }

        [JsonPropertyName("bbs")]
        public Pdf Bbs { get; set; }

        [JsonPropertyName("csf")]
        public Pdf Csf { get; set; }

        [JsonPropertyName("ftr")]
        public Pdf Ftr { get; set; }

        [JsonPropertyName("gtn")]
        public Pdf Gtn { get; set; }

        [JsonPropertyName("vm5")]
        public Pdf Vm5 { get; set; }

        [JsonPropertyName("vmx")]
        public Pdf Vmx { get; set; }

        [JsonPropertyName("ffa")]
        public Pdf Ffa { get; set; }

        [JsonPropertyName("fsc")]
        public Pdf Fsc { get; set; }

        [JsonPropertyName("fs9")]
        public Pdf Fs9 { get; set; }

        [JsonPropertyName("mfs")]
        public Pdf Mfs { get; set; }

        [JsonPropertyName("mfn")]
        public Pdf Mfn { get; set; }

        [JsonPropertyName("fsl")]
        public Pdf Fsl { get; set; }

        [JsonPropertyName("fsx")]
        public Pdf Fsx { get; set; }

        [JsonPropertyName("fsn")]
        public Pdf Fsn { get; set; }

        [JsonPropertyName("kml")]
        public Pdf Kml { get; set; }

        [JsonPropertyName("ify")]
        public Pdf Ify { get; set; }

        [JsonPropertyName("i74")]
        public Pdf I74 { get; set; }

        [JsonPropertyName("ifa")]
        public Pdf Ifa { get; set; }

        [JsonPropertyName("inb")]
        public Pdf Inb { get; set; }

        [JsonPropertyName("ivo")]
        public Pdf Ivo { get; set; }

        [JsonPropertyName("xvd")]
        public Pdf Xvd { get; set; }

        [JsonPropertyName("xvp")]
        public Pdf Xvp { get; set; }

        [JsonPropertyName("ixg")]
        public Pdf Ixg { get; set; }

        [JsonPropertyName("jar")]
        public Pdf Jar { get; set; }

        [JsonPropertyName("jhe")]
        public Pdf Jhe { get; set; }

        [JsonPropertyName("jfb")]
        public Pdf Jfb { get; set; }

        [JsonPropertyName("mdr")]
        public Pdf Mdr { get; set; }

        [JsonPropertyName("mda")]
        public Pdf Mda { get; set; }

        [JsonPropertyName("lvd")]
        public Pdf Lvd { get; set; }

        [JsonPropertyName("mjc")]
        public Pdf Mjc { get; set; }

        [JsonPropertyName("mjq")]
        public Pdf Mjq { get; set; }

        [JsonPropertyName("atm")]
        public Pdf Atm { get; set; }

        [JsonPropertyName("mvz")]
        public Pdf Mvz { get; set; }

        [JsonPropertyName("vms")]
        public Pdf Vms { get; set; }

        [JsonPropertyName("pmo")]
        public Pdf Pmo { get; set; }

        [JsonPropertyName("pmr")]
        public Pdf Pmr { get; set; }

        [JsonPropertyName("pmw")]
        public Pdf Pmw { get; set; }

        [JsonPropertyName("pgt")]
        public Pdf Pgt { get; set; }

        [JsonPropertyName("mga")]
        public Pdf Mga { get; set; }

        [JsonPropertyName("psm")]
        public Pdf Psm { get; set; }

        [JsonPropertyName("qty")]
        public Pdf Qty { get; set; }

        [JsonPropertyName("rmd")]
        public Pdf Rmd { get; set; }

        [JsonPropertyName("sbr")]
        public Pdf Sbr { get; set; }

        [JsonPropertyName("sfp")]
        public Pdf Sfp { get; set; }

        [JsonPropertyName("tdg")]
        public Pdf Tdg { get; set; }

        [JsonPropertyName("tfd")]
        public Pdf Tfd { get; set; }

        [JsonPropertyName("ufc")]
        public Pdf Ufc { get; set; }

        [JsonPropertyName("vas")]
        public Pdf Vas { get; set; }

        [JsonPropertyName("vfp")]
        public Pdf Vfp { get; set; }

        [JsonPropertyName("wae")]
        public Pdf Wae { get; set; }

        [JsonPropertyName("xfm")]
        public Pdf Xfm { get; set; }

        [JsonPropertyName("xpe")]
        public Pdf Xpe { get; set; }

        [JsonPropertyName("xpn")]
        public Pdf Xpn { get; set; }

        [JsonPropertyName("xp9")]
        public Pdf Xp9 { get; set; }

        [JsonPropertyName("zbo")]
        public Pdf Zbo { get; set; }
    }

    public partial class Fuel
    {
        [JsonPropertyName("taxi")]
        public string Taxi { get; set; }

        [JsonPropertyName("enroute_burn")]
        public string EnrouteBurn { get; set; }

        [JsonPropertyName("contingency")]
        public string Contingency { get; set; }

        [JsonPropertyName("alternate_burn")]
        public string AlternateBurn { get; set; }

        [JsonPropertyName("reserve")]
        public string Reserve { get; set; }

        [JsonPropertyName("etops")]
        public string Etops { get; set; }

        [JsonPropertyName("extra")]
        public string Extra { get; set; }

        [JsonPropertyName("extra_required")]
        public string ExtraRequired { get; set; }

        [JsonPropertyName("extra_optional")]
        public string ExtraOptional { get; set; }

        [JsonPropertyName("min_takeoff")]
        public string MinTakeoff { get; set; }

        [JsonPropertyName("plan_takeoff")]
        public string PlanTakeoff { get; set; }

        [JsonPropertyName("plan_ramp")]
        public string PlanRamp { get; set; }

        [JsonPropertyName("plan_landing")]
        public string PlanLanding { get; set; }

        [JsonPropertyName("avg_fuel_flow")]
        public string AvgFuelFlow { get; set; }

        [JsonPropertyName("max_tanks")]
        public string MaxTanks { get; set; }
    }

    public partial class FuelExtra
    {
        [JsonPropertyName("bucket")]
        public List<Bucket> Bucket { get; set; }
    }

    public partial class Bucket
    {
        [JsonPropertyName("label")]
        public string Label { get; set; }

        [JsonPropertyName("fuel")]
        public string Fuel { get; set; }

        [JsonPropertyName("time")]
        public string Time { get; set; }

        [JsonPropertyName("required")]
        public bool BucketRequired { get; set; }
    }

    public partial class General
    {
        [JsonPropertyName("release")]
        public string Release { get; set; }

        [JsonPropertyName("icao_airline")]
        public string IcaoAirline { get; set; }

        [JsonPropertyName("flight_number")]
        public string FlightNumber { get; set; }

        [JsonPropertyName("is_etops")]
        public string IsEtops { get; set; }

        [JsonPropertyName("dx_rmk")]
        public List<string> DxRmk { get; set; }

        [JsonPropertyName("sys_rmk")]
        public List<object> SysRmk { get; set; }

        [JsonPropertyName("is_detailed_profile")]
        public string IsDetailedProfile { get; set; }

        [JsonPropertyName("cruise_profile")]
        public string CruiseProfile { get; set; }

        [JsonPropertyName("climb_profile")]
        public string ClimbProfile { get; set; }

        [JsonPropertyName("descent_profile")]
        public string DescentProfile { get; set; }

        [JsonPropertyName("alternate_profile")]
        public string AlternateProfile { get; set; }

        [JsonPropertyName("reserve_profile")]
        public string ReserveProfile { get; set; }

        [JsonPropertyName("costindex")]
        public string Costindex { get; set; }

        [JsonPropertyName("cont_rule")]
        public string ContRule { get; set; }

        [JsonPropertyName("initial_altitude")]
        public string InitialAltitude { get; set; }

        [JsonPropertyName("stepclimb_string")]
        public string StepclimbString { get; set; }

        [JsonPropertyName("avg_temp_dev")]
        public string AvgTempDev { get; set; }

        [JsonPropertyName("avg_tropopause")]
        public string AvgTropopause { get; set; }

        [JsonPropertyName("avg_wind_comp")]
        public string AvgWindComp { get; set; }

        [JsonPropertyName("avg_wind_dir")]
        public string AvgWindDir { get; set; }

        [JsonPropertyName("avg_wind_spd")]
        public string AvgWindSpd { get; set; }

        [JsonPropertyName("gc_distance")]
        public string GcDistance { get; set; }

        [JsonPropertyName("route_distance")]
        public string RouteDistance { get; set; }

        [JsonPropertyName("air_distance")]
        public string AirDistance { get; set; }

        [JsonPropertyName("total_burn")]
        public string TotalBurn { get; set; }

        [JsonPropertyName("cruise_tas")]
        public string CruiseTas { get; set; }

        [JsonPropertyName("cruise_mach")]
        public string CruiseMach { get; set; }

        [JsonPropertyName("passengers")]
        public string Passengers { get; set; }

        [JsonPropertyName("route")]
        public string Route { get; set; }

        [JsonPropertyName("route_ifps")]
        public string RouteIfps { get; set; }

        [JsonPropertyName("route_navigraph")]
        public string RouteNavigraph { get; set; }
    }

    public partial class Images
    {
        [JsonPropertyName("directory")]
        public Uri Directory { get; set; }

        [JsonPropertyName("map")]
        public List<Pdf> Map { get; set; }
    }

    public partial class Impact
    {
        [JsonPropertyName("time_enroute")]
        public string TimeEnroute { get; set; }

        [JsonPropertyName("time_difference")]
        public string TimeDifference { get; set; }

        [JsonPropertyName("enroute_burn")]
        public string EnrouteBurn { get; set; }

        [JsonPropertyName("burn_difference")]
        public string BurnDifference { get; set; }

        [JsonPropertyName("ramp_fuel")]
        public string RampFuel { get; set; }

        [JsonPropertyName("initial_fl")]
        public string InitialFl { get; set; }

        [JsonPropertyName("initial_tas")]
        public string InitialTas { get; set; }

        [JsonPropertyName("initial_mach")]
        public string InitialMach { get; set; }

        [JsonPropertyName("cost_index")]
        public string CostIndex { get; set; }
    }

    public partial class Links
    {
        [JsonPropertyName("skyvector")]
        public Uri Skyvector { get; set; }
    }

    public partial class Navlog
    {
        [JsonPropertyName("ident")]
        public string Ident { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("icao_region")]
        public string IcaoRegion { get; set; }

        [JsonPropertyName("frequency")]
        public string Frequency { get; set; }

        [JsonPropertyName("pos_lat")]
        public string PosLat { get; set; }

        [JsonPropertyName("pos_long")]
        public string PosLong { get; set; }

        [JsonPropertyName("stage")]
        public string Stage { get; set; }

        [JsonPropertyName("via_airway")]
        public string ViaAirway { get; set; }

        [JsonPropertyName("is_sid_star")]
        public string IsSidStar { get; set; }

        [JsonPropertyName("distance")]
        public string Distance { get; set; }

        [JsonPropertyName("track_true")]
        public string TrackTrue { get; set; }

        [JsonPropertyName("track_mag")]
        public string TrackMag { get; set; }

        [JsonPropertyName("heading_true")]
        public string HeadingTrue { get; set; }

        [JsonPropertyName("heading_mag")]
        public string HeadingMag { get; set; }

        [JsonPropertyName("altitude_feet")]
        public string AltitudeFeet { get; set; }

        [JsonPropertyName("ind_airspeed")]
        public string IndAirspeed { get; set; }

        [JsonPropertyName("true_airspeed")]
        public string TrueAirspeed { get; set; }

        [JsonPropertyName("mach")]
        public string Mach { get; set; }

        [JsonPropertyName("mach_thousandths")]
        public string MachThousandths { get; set; }

        [JsonPropertyName("wind_component")]
        public string WindComponent { get; set; }

        [JsonPropertyName("groundspeed")]
        public string Groundspeed { get; set; }

        [JsonPropertyName("time_leg")]
        public string TimeLeg { get; set; }

        [JsonPropertyName("time_total")]
        public string TimeTotal { get; set; }

        [JsonPropertyName("fuel_flow")]
        public string FuelFlow { get; set; }

        [JsonPropertyName("fuel_leg")]
        public string FuelLeg { get; set; }

        [JsonPropertyName("fuel_totalused")]
        public string FuelTotalused { get; set; }

        [JsonPropertyName("fuel_min_onboard")]
        public string FuelMinOnboard { get; set; }

        [JsonPropertyName("fuel_plan_onboard")]
        public string FuelPlanOnboard { get; set; }

        [JsonPropertyName("oat")]
        public string Oat { get; set; }

        [JsonPropertyName("oat_isa_dev")]
        public string OatIsaDev { get; set; }

        [JsonPropertyName("wind_dir")]
        public string WindDir { get; set; }

        [JsonPropertyName("wind_spd")]
        public string WindSpd { get; set; }

        [JsonPropertyName("shear")]
        public string Shear { get; set; }

        [JsonPropertyName("tropopause_feet")]
        public string TropopauseFeet { get; set; }

        [JsonPropertyName("ground_height")]
        public string GroundHeight { get; set; }

        [JsonPropertyName("mora")]
        public string Mora { get; set; }

        [JsonPropertyName("fir")]
        public string Fir { get; set; }

        [JsonPropertyName("fir_units")]
        public string FirUnits { get; set; }

        [JsonPropertyName("fir_valid_levels")]
        public string FirValidLevels { get; set; }

        [JsonPropertyName("wind_data")]
        public List<WindDatum> WindData { get; set; }

        [JsonPropertyName("fir_crossing")]
        public List<FirCrossing> FirCrossing { get; set; }
    }

    public partial class FirCrossing
    {
        [JsonPropertyName("fir_icao")]
        public string FirIcao { get; set; }

        [JsonPropertyName("fir_name")]
        public string FirName { get; set; }

        [JsonPropertyName("pos_lat_entry")]
        public string PosLatEntry { get; set; }

        [JsonPropertyName("pos_long_entry")]
        public string PosLongEntry { get; set; }
    }

    public partial class WindDatum
    {
        [JsonPropertyName("altitude")]
        public string Altitude { get; set; }

        [JsonPropertyName("wind_dir")]
        public string WindDir { get; set; }

        [JsonPropertyName("wind_spd")]
        public string WindSpd { get; set; }

        [JsonPropertyName("oat")]
        public string Oat { get; set; }
    }

    public partial class SimbriefImportNotam
    {
        [JsonPropertyName("source_id")]
        public string SourceId { get; set; }

        [JsonPropertyName("account_id")]
        public string AccountId { get; set; }

        [JsonPropertyName("notam_id")]
        public string NotamId { get; set; }

        [JsonPropertyName("notam_part")]
        public string NotamPart { get; set; }

        [JsonPropertyName("cns_location_id")]
        public string CnsLocationId { get; set; }

        [JsonPropertyName("icao_id")]
        public string IcaoId { get; set; }

        [JsonPropertyName("icao_name")]
        public string IcaoName { get; set; }

        [JsonPropertyName("total_parts")]
        public string TotalParts { get; set; }

        [JsonPropertyName("notam_created_dtg")]
        public string NotamCreatedDtg { get; set; }

        [JsonPropertyName("notam_effective_dtg")]
        public string NotamEffectiveDtg { get; set; }

        [JsonPropertyName("notam_expire_dtg")]
        public string NotamExpireDtg { get; set; }

        [JsonPropertyName("notam_lastmod_dtg")]
        public string NotamLastmodDtg { get; set; }

        [JsonPropertyName("notam_inserted_dtg")]
        public string NotamInsertedDtg { get; set; }

        [JsonPropertyName("notam_text")]
        public string NotamText { get; set; }

        [JsonPropertyName("notam_report")]
        public string NotamReport { get; set; }

        [JsonPropertyName("notam_nrc")]
        public string NotamNrc { get; set; }

        [JsonPropertyName("notam_qcode")]
        public object NotamQcode { get; set; }

        [JsonPropertyName("notam_expire_dtg_estimated")]
        public string NotamExpireDtgEstimated { get; set; }
    }

    public partial class Origin
    {
        [JsonPropertyName("icao_code")]
        public string IcaoCode { get; set; }

        [JsonPropertyName("iata_code")]
        public string IataCode { get; set; }

        [JsonPropertyName("faa_code")]
        public string FaaCode { get; set; }

        [JsonPropertyName("icao_region")]
        public string IcaoRegion { get; set; }

        [JsonPropertyName("elevation")]
        public string Elevation { get; set; }

        [JsonPropertyName("pos_lat")]
        public string PosLat { get; set; }

        [JsonPropertyName("pos_long")]
        public string PosLong { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("timezone")]
        public string Timezone { get; set; }

        [JsonPropertyName("plan_rwy")]
        public string PlanRwy { get; set; }

        [JsonPropertyName("trans_alt")]
        public string TransAlt { get; set; }

        [JsonPropertyName("trans_level")]
        public string TransLevel { get; set; }

        [JsonPropertyName("metar")]
        public string Metar { get; set; }

        [JsonPropertyName("metar_time")]
        public object MetarTime { get; set; }

        [JsonPropertyName("metar_category")]
        public object MetarCategory { get; set; }

        [JsonPropertyName("metar_visibility")]
        public object MetarVisibility { get; set; }

        [JsonPropertyName("metar_ceiling")]
        public object MetarCeiling { get; set; }

        [JsonPropertyName("taf")]
        public string Taf { get; set; }

        [JsonPropertyName("taf_time")]
        public object TafTime { get; set; }

        [JsonPropertyName("atis")]
        public List<object> Atis { get; set; }

        [JsonPropertyName("notam")]
        public List<AirportNotam> Notam { get; set; }
    }

    public partial class AirportNotam
    {
        [JsonPropertyName("source_id")]
        public string SourceId { get; set; }

        [JsonPropertyName("account_id")]
        public string AccountId { get; set; }

        [JsonPropertyName("notam_id")]
        public string NotamId { get; set; }

        [JsonPropertyName("location_id")]
        public string LocationId { get; set; }

        [JsonPropertyName("location_icao")]
        public string LocationIcao { get; set; }

        [JsonPropertyName("location_name")]
        public string LocationName { get; set; }

        [JsonPropertyName("location_type")]
        public string LocationType { get; set; }

        [JsonPropertyName("date_created")]
        public string DateCreated { get; set; }

        [JsonPropertyName("date_effective")]
        public string DateEffective { get; set; }

        /// <summary>
        /// WARNING: This can be either an ISO formatted date or a boolean, I guess indicating there is no expiry date.
        /// </summary>
        [JsonPropertyName("date_expire")]
        public object DateExpire { get; set; }

        [JsonPropertyName("date_expire_is_estimated")]
        public bool DateExpireIsEstimated { get; set; }

        [JsonPropertyName("date_modified")]
        public string DateModified { get; set; }

        [JsonPropertyName("notam_schedule")]
        public string NotamSchedule { get; set; }

        [JsonPropertyName("notam_html")]
        public string NotamHtml { get; set; }

        [JsonPropertyName("notam_text")]
        public string NotamText { get; set; }

        [JsonPropertyName("notam_raw")]
        public string NotamRaw { get; set; }

        [JsonPropertyName("notam_nrc")]
        public string NotamNrc { get; set; }

        [JsonPropertyName("notam_qcode")]
        public object NotamQcode { get; set; }

        [JsonPropertyName("notam_qcode_category")]
        public string NotamQcodeCategory { get; set; }

        [JsonPropertyName("notam_qcode_subject")]
        public object NotamQcodeSubject { get; set; }

        [JsonPropertyName("notam_qcode_status")]
        public object NotamQcodeStatus { get; set; }

        [JsonPropertyName("notam_is_obstacle")]
        public bool NotamIsObstacle { get; set; }
    }

    public partial class Params
    {
        [JsonPropertyName("request_id")]
        public string RequestId { get; set; }

        [JsonPropertyName("user_id")]
        public string UserId { get; set; }

        [JsonPropertyName("time_generated")]
        public string TimeGenerated { get; set; }

        [JsonPropertyName("static_id")]
        public string StaticId { get; set; }

        [JsonPropertyName("xml_file")]
        public Uri XmlFile { get; set; }

        [JsonPropertyName("ofp_layout")]
        public string OfpLayout { get; set; }

        [JsonPropertyName("airac")]
        public string Airac { get; set; }

        [JsonPropertyName("units")]
        public string Units { get; set; }
    }

    public partial class Prefile
    {
        [JsonPropertyName("vatsim")]
        public Ivao Vatsim { get; set; }

        [JsonPropertyName("ivao")]
        public Ivao Ivao { get; set; }

        [JsonPropertyName("pilotedge")]
        public Ivao Pilotedge { get; set; }

        [JsonPropertyName("poscon")]
        public Ivao Poscon { get; set; }
    }

    public partial class Ivao
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("site")]
        public string Site { get; set; }

        [JsonPropertyName("link")]
        public Uri Link { get; set; }

        [JsonPropertyName("form")]
        public string Form { get; set; }
    }

    public partial class Sigmet
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("loc")]
        public string Loc { get; set; }

        [JsonPropertyName("address")]
        public string Address { get; set; }

        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("fir")]
        public string Fir { get; set; }

        [JsonPropertyName("fir_name")]
        public string FirName { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("hazard")]
        public string Hazard { get; set; }

        [JsonPropertyName("qualifier")]
        public string Qualifier { get; set; }

        [JsonPropertyName("issued")]
        public string Issued { get; set; }

        [JsonPropertyName("start")]
        public string Start { get; set; }

        [JsonPropertyName("end")]
        public string End { get; set; }

        [JsonPropertyName("text")]
        public string Text { get; set; }
    }

    public partial class Text
    {
        [JsonPropertyName("nat_tracks")]
        public string NatTracks { get; set; }

        [JsonPropertyName("tlr_section")]
        public string TlrSection { get; set; }

        [JsonPropertyName("plan_html")]
        public string PlanHtml { get; set; }
    }

    public partial class Times
    {
        [JsonPropertyName("est_time_enroute")]
        public string EstTimeEnroute { get; set; }

        [JsonPropertyName("sched_time_enroute")]
        public string SchedTimeEnroute { get; set; }

        [JsonPropertyName("sched_out")]
        public string SchedOut { get; set; }

        [JsonPropertyName("sched_off")]
        public string SchedOff { get; set; }

        [JsonPropertyName("sched_on")]
        public string SchedOn { get; set; }

        [JsonPropertyName("sched_in")]
        public string SchedIn { get; set; }

        [JsonPropertyName("sched_block")]
        public string SchedBlock { get; set; }

        [JsonPropertyName("est_out")]
        public string EstOut { get; set; }

        [JsonPropertyName("est_off")]
        public string EstOff { get; set; }

        [JsonPropertyName("est_on")]
        public string EstOn { get; set; }

        [JsonPropertyName("est_in")]
        public string EstIn { get; set; }

        [JsonPropertyName("est_block")]
        public string EstBlock { get; set; }

        [JsonPropertyName("orig_timezone")]
        public string OrigTimezone { get; set; }

        [JsonPropertyName("dest_timezone")]
        public string DestTimezone { get; set; }

        [JsonPropertyName("taxi_out")]
        public string TaxiOut { get; set; }

        [JsonPropertyName("taxi_in")]
        public string TaxiIn { get; set; }

        [JsonPropertyName("reserve_time")]
        public string ReserveTime { get; set; }

        [JsonPropertyName("endurance")]
        public string Endurance { get; set; }

        [JsonPropertyName("contfuel_time")]
        public string ContfuelTime { get; set; }

        [JsonPropertyName("etopsfuel_time")]
        public string EtopsfuelTime { get; set; }

        [JsonPropertyName("extrafuel_time")]
        public string ExtrafuelTime { get; set; }
    }

    public partial class Weather
    {
        [JsonPropertyName("orig_metar")]
        public string OrigMetar { get; set; }

        [JsonPropertyName("orig_taf")]
        public string OrigTaf { get; set; }

        [JsonPropertyName("dest_metar")]
        public string DestMetar { get; set; }

        [JsonPropertyName("dest_taf")]
        public string DestTaf { get; set; }

        [JsonPropertyName("altn_metar")]
        public List<string> AltnMetar { get; set; }

        [JsonPropertyName("altn_taf")]
        public List<string> AltnTaf { get; set; }

        [JsonPropertyName("toaltn_metar")]
        public string ToaltnMetar { get; set; }

        [JsonPropertyName("toaltn_taf")]
        public string ToaltnTaf { get; set; }

        [JsonPropertyName("eualtn_metar")]
        public string EualtnMetar { get; set; }

        [JsonPropertyName("eualtn_taf")]
        public string EualtnTaf { get; set; }

        [JsonPropertyName("etops_metar")]
        public List<object> EtopsMetar { get; set; }

        [JsonPropertyName("etops_taf")]
        public List<object> EtopsTaf { get; set; }
    }

    public partial class Weights
    {
        [JsonPropertyName("oew")]
        public string Oew { get; set; }

        [JsonPropertyName("pax_count")]
        public string PaxCount { get; set; }

        [JsonPropertyName("bag_count")]
        public string BagCount { get; set; }

        [JsonPropertyName("pax_count_actual")]
        public string PaxCountActual { get; set; }

        [JsonPropertyName("bag_count_actual")]
        public string BagCountActual { get; set; }

        [JsonPropertyName("pax_weight")]
        public string PaxWeight { get; set; }

        [JsonPropertyName("bag_weight")]
        public string BagWeight { get; set; }

        [JsonPropertyName("freight_added")]
        public string FreightAdded { get; set; }

        [JsonPropertyName("cargo")]
        public string Cargo { get; set; }

        [JsonPropertyName("payload")]
        public string Payload { get; set; }

        [JsonPropertyName("est_zfw")]
        public string EstZfw { get; set; }

        [JsonPropertyName("max_zfw")]
        public string MaxZfw { get; set; }

        [JsonPropertyName("est_tow")]
        public string EstTow { get; set; }

        [JsonPropertyName("max_tow")]
        public string MaxTow { get; set; }

        [JsonPropertyName("max_tow_struct")]
        public string MaxTowStruct { get; set; }

        [JsonPropertyName("tow_limit_code")]
        public string TowLimitCode { get; set; }

        [JsonPropertyName("est_ldw")]
        public string EstLdw { get; set; }

        [JsonPropertyName("max_ldw")]
        public string MaxLdw { get; set; }

        [JsonPropertyName("est_ramp")]
        public string EstRamp { get; set; }
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
