title: FFLOG
pilot: thefipster
subtitle: fipster's flight log
description: Bloglike Microsoft Flight Simulator Tracking System
social: https://github.com/thefipster
permalink: flights/:title:output_ext

markdown: kramdown

sass: false

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- node_modules
- rollup.config.js
- package.json
- package-lock.json
- examples
- _sass
- _scripts
