# site settings
title: FFLOG
subtitle: fipster's flight log
description: Bloglike Microsoft Flight Simulator Tracking System
github: https://github.com/thefipster
permalink: flights/:title:output_ext

tiles-source: pages
tiles-count: 6

markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- node_modules
- rollup.config.js
- package.json
- package-lock.json
- examples
