source 'https://rubygems.org'

gem 'jekyll', '~> 4.2'
#gem 'wdm', '~> 0.1.0' if Gem.win_platform?
gem "webrick", "~> 1.8"
gem 'jekyll-watch'

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

group :jekyll_plugins do
  gem 'jekyll-timeago', '~> 0.13.1'
end

